import {
  User,
  CreatorBusiness,
  BrandProfile,
  PlanEntitlement,
  Subscription,
  Campaign,
  ContentAsset,
  PublishingReceipt,
  Post,
  NotificationItem,
  ModerationReport,
  ConnectedSocialAccount,
  AdminTelemetry,
} from './types';

export const INITIAL_USER: User = {
  id: 'usr-1001',
  email: 'alex@example.com',
  fullName: 'Alex Rivera',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
  systemRole: 'SUPERADMIN',
  createdAt: '2026-01-15T08:00:00Z',
};

export const INITIAL_BUSINESSES: CreatorBusiness[] = [
  {
    id: 'biz-01',
    name: 'FinTech Pulse',
    handle: 'fintechpulse',
    bio: 'Unpacking algorithmic trading, institutional DeFi, and next-gen banking architecture. Published daily.',
    avatarUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=256&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?auto=format&fit=crop&w=1200&q=80',
    niche: 'FinTech & Banking',
    websiteUrl: 'https://fintechpulse.example.com',
    brandVoiceSummary: 'Authoritative, data-grounded, analytical with concise institutional clarity.',
    targetAudience: 'Venture investors, FinTech product leaders, and quant engineers.',
    businessObjectives: 'Build high-tier thought leadership and drive investor newsletter signups.',
    followerCount: 3840,
    followingCount: 142,
    isVerified: true,
    role: 'OWNER',
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'biz-02',
    name: 'Creator Craft',
    handle: 'creatorcraft',
    bio: 'Actionable monetization frameworks and audience distribution playbooks for modern independent creators.',
    avatarUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=256&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
    niche: 'Creator Economy',
    websiteUrl: 'https://creatorcraft.example.com',
    brandVoiceSummary: 'Inspiring, tactical, conversational, direct and transparent.',
    targetAudience: 'Solo founders, digital educators, newsletter writers, and consultants.',
    businessObjectives: 'Establish community authority and increase course enrollments.',
    followerCount: 2150,
    followingCount: 290,
    isVerified: true,
    role: 'OWNER',
    createdAt: '2026-03-10T14:30:00Z',
  },
  {
    id: 'biz-03',
    name: 'CloudScale SaaS',
    handle: 'cloudscale',
    bio: 'B2B enterprise scaling tactics, pricing models, and churn reduction strategies.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    niche: 'B2B Software',
    websiteUrl: 'https://cloudscalesaas.example.com',
    brandVoiceSummary: 'Professional, empirical, executive-level, clear ROI focus.',
    targetAudience: 'SaaS CEOs, VP Sales, and Customer Success Directors.',
    businessObjectives: 'Demo requests for enterprise retention audit platform.',
    followerCount: 1120,
    followingCount: 88,
    isVerified: false,
    role: 'OWNER',
    createdAt: '2026-05-18T09:00:00Z',
  },
];

export const INITIAL_BRAND_PROFILES: Record<string, BrandProfile> = {
  'biz-01': {
    businessId: 'biz-01',
    archetype: 'The Analytical Expert',
    primaryTone: 'Authoritative',
    secondaryTone: 'Professional',
    forbiddenTerms: ['synergy', 'game-changer', 'revolutionize', 'supercharge'],
    favoriteTopics: ['Algorithmic Trading', 'Open Banking', 'Real-time Payments', 'Treasury Tech'],
    sampleHooks: [
      '94% of tier-1 banks are overpaying for liquidity routing. Here is the mathematical proof.',
      'Why modern clearinghouses are quietly ditching legacy messaging systems.',
    ],
    ctaPatterns: [
      'Read our complete liquidity breakdown on HeliSocial or join 12,000 finance leaders on our newsletter.',
    ],
    customInstructions: 'Always cite empirical market realities. Never use sensationalist buzzwords. Keep formatting spaced.',
  },
  'biz-02': {
    businessId: 'biz-02',
    archetype: 'The Inspiring Mentor',
    primaryTone: 'Conversational',
    secondaryTone: 'Bold',
    forbiddenTerms: ['hustle 24/7', 'get rich quick', 'passive income overnight'],
    favoriteTopics: ['Newsletter Growth', 'Digital Products', 'Content Repurposing', 'Community Retention'],
    sampleHooks: [
      'Stop creating 10 new posts a week. Repurpose 1 deep essay into a 7-channel flywheel.',
      'The single biggest mistake creator-businesses make when pricing their first $100 offer.',
    ],
    ctaPatterns: [
      'Save this post for your next content sprint, and follow @creatorcraft for daily breakdowns.',
    ],
    customInstructions: 'Speak peer-to-peer. Use punchy 1-sentence paragraphs. Use bulleted takeaways.',
  },
  'biz-03': {
    businessId: 'biz-03',
    archetype: 'The Practical Tactician',
    primaryTone: 'Professional',
    secondaryTone: 'Educational',
    forbiddenTerms: ['disruptive', 'unicorn', 'magic bullet'],
    favoriteTopics: ['Net Revenue Retention', 'SaaS Pricing', 'Expansion Revenue', 'Cohort Churn'],
    sampleHooks: [
      'If your NRR is under 110%, you do not have a sales problem—you have an onboarding leak.',
      '3 pricing tier mistakes that cost seed-stage SaaS companies up to 40% of their ARR.',
    ],
    ctaPatterns: [
      'Drop your biggest onboarding bottleneck in the comments or book an architecture audit.',
    ],
    customInstructions: 'Focus on metrics like CAC, LTV, NRR, and payback periods. Keep prose executive-grade.',
  },
};

export const PLANS: PlanEntitlement[] = [
  {
    id: 'free',
    name: 'Free Trial',
    monthlyPrice: 0,
    maxBusinesses: 1,
    monthlyAiCredits: 50,
    storageMb: 100,
    hasAnalytics: false,
    hasExternalPublishing: false,
    hasTeamRoles: false,
    description: 'Explore the AI studio, manage 1 creator business, and participate in the community.',
  },
  {
    id: 'creator',
    name: 'Creator',
    monthlyPrice: 29,
    maxBusinesses: 1,
    monthlyAiCredits: 350,
    storageMb: 1024,
    hasAnalytics: true,
    hasExternalPublishing: true,
    hasTeamRoles: false,
    badge: 'POPULAR',
    description: 'Full AI campaign suite, dedicated publishing receipts, and analytics for solo creators.',
  },
  {
    id: 'business',
    name: 'Business',
    monthlyPrice: 79,
    maxBusinesses: 3,
    monthlyAiCredits: 1200,
    storageMb: 4096,
    hasAnalytics: true,
    hasExternalPublishing: true,
    hasTeamRoles: true,
    badge: 'RECOMMENDED',
    description: 'Manage up to 3 separate Creator Businesses with independent brand voices and campaigns.',
  },
  {
    id: 'agency',
    name: 'Agency',
    monthlyPrice: 199,
    maxBusinesses: 10,
    monthlyAiCredits: 4000,
    storageMb: 16384,
    hasAnalytics: true,
    hasExternalPublishing: true,
    hasTeamRoles: true,
    description: 'High-volume studio for managing up to 10 client brands with role-based team access.',
  },
];

export const INITIAL_SUBSCRIPTION: Subscription = {
  planId: 'business',
  status: 'active',
  currentPeriodEnd: '2026-10-15T00:00:00Z',
  aiCreditsUsed: 380,
  aiCreditsTotal: 1200,
};

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: 'cmp-01',
    businessId: 'biz-01',
    title: 'Q4 Institutional AI Banking Infrastructure',
    description: 'Multi-channel campaign exploring how core banking switches integrate real-time LLM risk scoring.',
    objective: 'Thought Leadership',
    status: 'ACTIVE',
    createdAt: '2026-09-02T11:00:00Z',
    updatedAt: '2026-09-15T16:30:00Z',
    assetCount: 6,
  },
  {
    id: 'cmp-02',
    businessId: 'biz-01',
    title: 'Treasury Automation Whitepaper Repurpose',
    description: 'Derived from 24-page PDF on cross-border liquidity routing.',
    objective: 'Lead Generation',
    status: 'COMPLETED',
    createdAt: '2026-08-14T09:15:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
    assetCount: 5,
  },
  {
    id: 'cmp-03',
    businessId: 'biz-02',
    title: 'Content Flywheel: From 1 Idea to 7 Platforms',
    description: 'Step-by-step operational guide showing creators how to avoid burnout with smart repurposing.',
    objective: 'Education',
    status: 'ACTIVE',
    createdAt: '2026-09-05T13:00:00Z',
    updatedAt: '2026-09-12T18:00:00Z',
    assetCount: 7,
  },
];

export const INITIAL_CONTENT_ASSETS: ContentAsset[] = [
  {
    id: 'ast-01',
    businessId: 'biz-01',
    campaignId: 'cmp-01',
    assetType: 'LINKEDIN_POST',
    title: 'The Hidden Latency of Legacy Core Banking',
    structuredPayload: {
      hook: 'Most tier-1 banks believe their core ledger runs in real-time. In reality, reconciliation takes 48 hours and millions in idle capital.',
      body: `Here are the 3 structural bottlenecks stopping legacy financial institutions from adopting instant settlement:\n\n1. Batch-file dependencies from mainframe architectures\n2. Fragmented KYC pipelines running asynchronously\n3. Redundant clearing intermediaries charging 18-35 bps per swap\n\nThe banks winning this decade are decoupling their ledgers into event-driven microservices with continuous risk scoring.`,
      cta: 'How is your treasury team preparing for the 2027 ISO 20022 mandate? Let us discuss below.',
    },
    plainTextVersion: `Most tier-1 banks believe their core ledger runs in real-time. In reality, reconciliation takes 48 hours and millions in idle capital.\n\nHere are the 3 structural bottlenecks stopping legacy financial institutions from adopting instant settlement:\n\n1. Batch-file dependencies from mainframe architectures\n2. Fragmented KYC pipelines running asynchronously\n3. Redundant clearing intermediaries charging 18-35 bps per swap\n\nThe banks winning this decade are decoupling their ledgers into event-driven microservices with continuous risk scoring.\n\nHow is your treasury team preparing for the 2027 ISO 20022 mandate? Let us discuss below.`,
    isArchived: false,
    createdAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'ast-02',
    businessId: 'biz-01',
    campaignId: 'cmp-01',
    assetType: 'LINKEDIN_CAROUSEL',
    title: '8-Slide Executive Deck: Modern Liquidity Routing',
    structuredPayload: {
      hook: '8 Rules for Modern Institutional Liquidity Routing (Swipe Through)',
      slides: [
        {
          slideNumber: 1,
          title: 'The Liquidity Trap',
          content: 'Why holding static capital reserves costs commercial banks up to $42M annually in lost yields.',
          visualNote: 'Contrast diagram: Static vs. Dynamic Liquidity Pools',
        },
        {
          slideNumber: 2,
          title: 'Rule 1: Continuous Rebalancing',
          content: 'Move from end-of-day batch processing to sub-second smart contract sweeps.',
          visualNote: 'Clean flow chart showing real-time ledger triggers',
        },
        {
          slideNumber: 3,
          title: 'Rule 2: Automated Route Splitting',
          content: 'Never send >$5M through a single clearing corridor during high volatility windows.',
          visualNote: 'Corridor map highlighting fee variations',
        },
        {
          slideNumber: 4,
          title: 'Rule 3: Algorithmic Slippage Guards',
          content: 'Integrate TWAP execution models into cross-currency FX treasury balances.',
          visualNote: 'Line graph showing execution efficiency',
        },
        {
          slideNumber: 5,
          title: 'Rule 4: Counterparty Health Checks',
          content: 'Real-time telemetry on tier-2 correspondent banking liquidity ratios.',
          visualNote: 'Dashboard mock with risk status flags',
        },
        {
          slideNumber: 6,
          title: 'Rule 5: Zero Manual Reconciliation',
          content: 'Automated cryptographic receipts for every cross-border settlement event.',
          visualNote: 'Verification check badge with audit timestamp',
        },
        {
          slideNumber: 7,
          title: 'The Business Impact',
          content: 'Institutions deploying this architecture cut operational overhead by 31% within 90 days.',
          visualNote: 'Bar comparison showing baseline vs. optimized margin',
        },
        {
          slideNumber: 8,
          title: 'Take Action Today',
          content: 'Download the full 24-page architectural framework from HeliSocial. Follow @fintechpulse.',
          visualNote: 'Author avatar and HeliSocial verified badge',
        },
      ],
      cta: 'Follow @fintechpulse for institutional fintech teardowns every Tuesday.',
    },
    plainTextVersion: '8-Slide Executive Deck: Modern Liquidity Routing. Slide 1 to 8 covering algorithmic treasury rebalancing.',
    isArchived: false,
    createdAt: '2026-09-11T14:10:00Z',
  },
  {
    id: 'ast-03',
    businessId: 'biz-01',
    campaignId: 'cmp-01',
    assetType: 'X_THREAD',
    title: '5-Tweet Breakdown on High-Frequency Clearing',
    structuredPayload: {
      hook: '1/5 The clearinghouse monopoly is quietly dissolving. Here is why the next generation of settlement networks will be invisible to retail consumers (and saving banks billions): 🧵',
      threadTweets: [
        '1/5 The clearinghouse monopoly is quietly dissolving. Here is why the next generation of settlement networks will be invisible to retail consumers (and saving banks billions): 🧵',
        '2/5 For 50 years, ACH and SWIFT operated as slow, message-passing protocols. They do not move money—they merely send promises to reconcile money later tonight.',
        '3/5 Modern event-driven ledgers change the paradigm: settlement AND messaging happen simultaneously. No daylight overdraft risk. Zero float lag.',
        '4/5 In 2025 alone, early-adopting institutions recaptured an estimated $3.2B in trapped collateral. The efficiency dividend is staggering.',
        '5/5 If your engineering team is still maintaining batch-FTP file transfers with legacy clearinghouses, you are carrying existential technical debt. Follow @fintechpulse for the full blueprint.',
      ],
      cta: 'Repost if you found this insightful. Bookmark for your next architecture review.',
    },
    plainTextVersion: '5-Tweet Breakdown on High-Frequency Clearing with data on ACH vs event-driven ledgers.',
    isArchived: false,
    createdAt: '2026-09-12T09:30:00Z',
  },
  {
    id: 'ast-04',
    businessId: 'biz-02',
    campaignId: 'cmp-03',
    assetType: 'QUICK_POSTS',
    title: '3 Viral Short Post Variations',
    structuredPayload: {
      quickPosts: [
        'Content burnout is not caused by working too hard. It is caused by starting from a blank page every morning. Systemize your source intake, and creation becomes pure curation.',
        'The best creators in 2026 do not write more. They write once, distribute into 7 structured assets, and spend 80% of their energy engaging with their audience.',
        'Audience is vanity. Community is leverage. Revenue is sanity. Focus on the relationships that compound over 3 years, not the 24-hour impression spikes.',
      ],
    },
    plainTextVersion: '3 Viral Short Post Variations on content burnout, audience leverage, and compound distribution.',
    isArchived: false,
    createdAt: '2026-09-13T16:00:00Z',
  },
];

export const INITIAL_RECEIPTS: PublishingReceipt[] = [
  {
    id: 'rec-901',
    businessId: 'biz-01',
    contentAssetId: 'ast-01',
    assetTitle: 'The Hidden Latency of Legacy Core Banking',
    assetType: 'LINKEDIN_POST',
    destinationPlatform: 'HELISOCIAL',
    status: 'PUBLISHED_TO_HELISOCIAL',
    internalPostId: 'post-101',
    timestamp: '2026-09-14T10:15:22Z',
  },
  {
    id: 'rec-902',
    businessId: 'biz-01',
    contentAssetId: 'ast-01',
    assetTitle: 'The Hidden Latency of Legacy Core Banking',
    assetType: 'LINKEDIN_POST',
    destinationPlatform: 'LINKEDIN',
    status: 'EXTERNALLY_PUBLISHED',
    externalPostId: 'urn:li:share:71982938491028',
    externalPostUrl: 'https://www.linkedin.com/feed/update/urn:li:activity:71982938491028',
    timestamp: '2026-09-14T10:16:05Z',
  },
  {
    id: 'rec-903',
    businessId: 'biz-01',
    contentAssetId: 'ast-03',
    assetTitle: '5-Tweet Breakdown on High-Frequency Clearing',
    assetType: 'X_THREAD',
    destinationPlatform: 'X',
    status: 'EXTERNALLY_PUBLISHED',
    externalPostId: '18492049281039',
    externalPostUrl: 'https://x.com/fintechpulse/status/18492049281039',
    timestamp: '2026-09-15T09:45:00Z',
  },
  {
    id: 'rec-904',
    businessId: 'biz-01',
    contentAssetId: 'ast-02',
    assetTitle: '8-Slide Executive Deck: Modern Liquidity Routing',
    assetType: 'LINKEDIN_CAROUSEL',
    destinationPlatform: 'HELISOCIAL',
    status: 'SAVED',
    timestamp: '2026-09-16T11:20:00Z',
  },
  {
    id: 'rec-905',
    businessId: 'biz-02',
    contentAssetId: 'ast-04',
    assetTitle: '3 Viral Short Post Variations',
    assetType: 'QUICK_POSTS',
    destinationPlatform: 'HELISOCIAL',
    status: 'PUBLISHED_TO_HELISOCIAL',
    internalPostId: 'post-102',
    timestamp: '2026-09-16T15:00:00Z',
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-101',
    businessId: 'biz-01',
    businessName: 'FinTech Pulse',
    businessHandle: 'fintechpulse',
    businessAvatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=256&q=80',
    body: `Most tier-1 banks believe their core ledger runs in real-time. In reality, reconciliation takes 48 hours and millions in idle capital.\n\nHere are the 3 structural bottlenecks stopping legacy financial institutions from adopting instant settlement:\n\n1. Batch-file dependencies from mainframe architectures\n2. Fragmented KYC pipelines running asynchronously\n3. Redundant clearing intermediaries charging 18-35 bps per swap\n\nThe institutions winning this decade are decoupling their ledgers into event-driven microservices with continuous risk scoring.`,
    visibility: 'PUBLIC',
    topicTag: '#fintech',
    reactions: { LIKE: 48, INSIGHTFUL: 29, FIRE: 14, CLAP: 11 },
    userReactions: ['INSIGHTFUL'],
    comments: [
      {
        id: 'cmt-1',
        postId: 'post-101',
        businessId: 'biz-03',
        businessName: 'CloudScale SaaS',
        businessHandle: 'cloudscale',
        businessAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
        body: 'Spot on. The batch reconciliation drag on enterprise cash flow is why B2B fintechs are winning market share from regional commercial banks.',
        createdAt: '2026-09-14T11:30:00Z',
      },
    ],
    commentCount: 1,
    saveCount: 18,
    isSavedByUser: true,
    receiptId: 'rec-901',
    externalUrl: 'https://www.linkedin.com/feed/update/urn:li:activity:71982938491028',
    publishedAt: '2026-09-14T10:15:22Z',
  },
  {
    id: 'post-102',
    businessId: 'biz-02',
    businessName: 'Creator Craft',
    businessHandle: 'creatorcraft',
    businessAvatar: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=256&q=80',
    body: `Content burnout is not caused by working too hard.\n\nIt is caused by starting from a blank page every single morning.\n\nSystemize your source intake: take 1 rich insight, repurpose it into a LinkedIn Carousel, an X Thread, 3 short posts, and a newsletter. Now you are operating a media business, not running on a hamster wheel.`,
    visibility: 'PUBLIC',
    topicTag: '#creator',
    reactions: { LIKE: 84, INSIGHTFUL: 37, FIRE: 42, CLAP: 25 },
    userReactions: ['FIRE', 'LIKE'],
    comments: [],
    commentCount: 0,
    saveCount: 41,
    isSavedByUser: false,
    receiptId: 'rec-905',
    publishedAt: '2026-09-16T15:00:00Z',
  },
  {
    id: 'post-103',
    businessId: 'biz-03',
    businessName: 'CloudScale SaaS',
    businessHandle: 'cloudscale',
    businessAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    body: `If your Net Revenue Retention (NRR) is sitting at 98%, throwing more SDRs at top-of-funnel leads is the fastest way to burn runway.\n\nFocus on Month 3 product adoption milestones. That is where 70% of downstream enterprise churn is decided.`,
    visibility: 'PUBLIC',
    topicTag: '#saas',
    reactions: { LIKE: 53, INSIGHTFUL: 61, FIRE: 19, CLAP: 8 },
    userReactions: [],
    comments: [],
    commentCount: 0,
    saveCount: 32,
    isSavedByUser: false,
    publishedAt: '2026-09-15T18:20:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    targetBusinessId: 'biz-01',
    actorBusinessName: 'Creator Craft',
    actorBusinessHandle: 'creatorcraft',
    actorAvatar: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=256&q=80',
    type: 'NEW_FOLLOWER',
    message: 'Creator Craft started following @fintechpulse.',
    isRead: false,
    createdAt: '2026-09-16T17:15:00Z',
  },
  {
    id: 'notif-2',
    targetBusinessId: 'biz-01',
    actorBusinessName: 'CloudScale SaaS',
    actorBusinessHandle: 'cloudscale',
    actorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    type: 'COMMENT',
    message: 'CloudScale SaaS commented on your post "The Hidden Latency of Legacy Core Banking".',
    referenceId: 'post-101',
    isRead: false,
    createdAt: '2026-09-14T11:30:00Z',
  },
  {
    id: 'notif-3',
    targetBusinessId: 'biz-01',
    actorBusinessName: 'HeliSocial System',
    actorBusinessHandle: 'helisocial',
    actorAvatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=256&q=80',
    type: 'PUBLISH_SUCCESS',
    message: 'Publishing receipt REC-902 confirmed: post successfully delivered to LinkedIn.',
    referenceId: 'rec-902',
    isRead: true,
    createdAt: '2026-09-14T10:16:05Z',
  },
];

export const INITIAL_MODERATION_REPORTS: ModerationReport[] = [
  {
    id: 'rep-01',
    reporterUserId: 'usr-999',
    targetType: 'POST',
    targetId: 'post-998',
    targetSummary: 'Promotional crypto pump scheme disguised as algorithmic trading advice',
    reason: 'SPAM',
    details: 'User repeatedly posted suspicious telegram invitation links in comments.',
    status: 'PENDING',
    createdAt: '2026-09-16T08:00:00Z',
  },
];

export const INITIAL_CONNECTED_SOCIALS: Record<string, ConnectedSocialAccount[]> = {
  'biz-01': [
    {
      id: 'soc-1',
      platform: 'LINKEDIN',
      accountName: 'FinTech Pulse Page',
      accountHandle: 'fintech-pulse-org',
      connectedAt: '2026-02-10T12:00:00Z',
      status: 'CONNECTED',
    },
    {
      id: 'soc-2',
      platform: 'X',
      accountName: 'FinTech Pulse',
      accountHandle: '@fintechpulse',
      connectedAt: '2026-02-12T14:00:00Z',
      status: 'CONNECTED',
    },
  ],
  'biz-02': [
    {
      id: 'soc-3',
      platform: 'LINKEDIN',
      accountName: 'Creator Craft Community',
      accountHandle: 'creator-craft',
      connectedAt: '2026-03-15T09:00:00Z',
      status: 'CONNECTED',
    },
  ],
  'biz-03': [],
};

export const INITIAL_ADMIN_TELEMETRY: AdminTelemetry = {
  mrrCents: 1485000, // $14,850 MRR
  totalUsers: 482,
  totalCreatorBusinesses: 820,
  activeSubscriptionsCount: 236,
  tierDistribution: {
    free: 246,
    creator: 124,
    business: 88,
    agency: 24,
  },
  totalAiCreditsConsumed: 412500,
  estimatedAiCostsUsd: 142.38,
  estimatedNetProfitUsd: 14707.62,
  totalPostsPublished: 3190,
  totalReceiptsCount: 4820,
  pendingReportsCount: 1,
};

export const CLEAN_BASELINE_USER: User = {
  id: 'usr-clean-01',
  email: 'founder@example.com',
  fullName: 'New Founder',
  avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=256&q=80',
  systemRole: 'SUPERADMIN',
  createdAt: '2026-09-01T00:00:00Z',
};

export const CLEAN_BASELINE_BUSINESSES: CreatorBusiness[] = [
  {
    id: 'biz-clean-01',
    name: 'My New Brand',
    handle: 'mynewbrand',
    bio: 'Newly initialized creator business on HeliSocial.',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=256&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=1200&q=80',
    niche: 'Digital Creator',
    websiteUrl: 'https://example.com',
    brandVoiceSummary: 'Clear, modern, and direct.',
    targetAudience: 'Community members and early adopters.',
    businessObjectives: 'Build first audience and test content reach.',
    followerCount: 0,
    followingCount: 0,
    isVerified: false,
    role: 'OWNER',
    createdAt: '2026-09-01T00:00:00Z',
  },
];

export const CLEAN_BASELINE_TELEMETRY: AdminTelemetry = {
  mrrCents: 0,
  totalUsers: 1,
  totalCreatorBusinesses: 1,
  activeSubscriptionsCount: 0,
  tierDistribution: {
    free: 1,
    creator: 0,
    business: 0,
    agency: 0,
  },
  totalAiCreditsConsumed: 0,
  estimatedAiCostsUsd: 0,
  estimatedNetProfitUsd: 0,
  totalPostsPublished: 0,
  totalReceiptsCount: 0,
  pendingReportsCount: 0,
};

export const CLEAN_BASELINE_SUBSCRIPTION: Subscription = {
  planId: 'free',
  status: 'active',
  currentPeriodEnd: '2026-12-31T23:59:59Z',
  aiCreditsUsed: 0,
  aiCreditsTotal: 50,
};

